services:
  - type: web
    name: todolist
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: todolist-db
          property: connectionString
databases:
  - name: todolist-db
    databaseName: todolist
    user: todolist_user
